sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t raintech/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raintech/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "react-travis-cicd"
  env: "react-travis-cicd-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-471112896660"
  bucket_path: "react-travis-cicd"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
